-- One-time Snowflake setup for the Springdale case study.
-- Run as ACCOUNTADMIN in a Snowsight worksheet.

USE ROLE ACCOUNTADMIN;

-- Warehouse: small, aggressive auto-suspend to protect trial credits
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
         AUTO_SUSPEND = 60
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE;

-- Databases
CREATE DATABASE IF NOT EXISTS SPRINGDALE_RAW;
CREATE DATABASE IF NOT EXISTS SPRINGDALE_ANALYTICS;

-- Schemas in ANALYTICS for dbt layers
CREATE SCHEMA IF NOT EXISTS SPRINGDALE_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS SPRINGDALE_ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS SPRINGDALE_ANALYTICS.MARTS;
CREATE SCHEMA IF NOT EXISTS SPRINGDALE_ANALYTICS.SEEDS;

-- Schema in RAW for Airbyte to land data
CREATE SCHEMA IF NOT EXISTS SPRINGDALE_RAW.IT_SOURCE;

-- Roles
CREATE ROLE IF NOT EXISTS LOADER_ROLE;
CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE;

-- Grants for LOADER_ROLE (Airbyte writes to RAW)
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LOADER_ROLE;
GRANT USAGE ON DATABASE SPRINGDALE_RAW TO ROLE LOADER_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE SPRINGDALE_RAW TO ROLE LOADER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE LOADER_ROLE;

-- Grants for TRANSFORMER_ROLE (dbt reads RAW, writes ANALYTICS)
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE SPRINGDALE_RAW TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPRINGDALE_RAW.IT_SOURCE TO ROLE TRANSFORMER_ROLE;

GRANT USAGE ON DATABASE SPRINGDALE_ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE SPRINGDALE_ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA SPRINGDALE_ANALYTICS.STAGING TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA SPRINGDALE_ANALYTICS.INTERMEDIATE TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA SPRINGDALE_ANALYTICS.MARTS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA SPRINGDALE_ANALYTICS.SEEDS TO ROLE TRANSFORMER_ROLE;

-- Grant both roles to the user
GRANT ROLE LOADER_ROLE TO USER PGANALYTICS;
GRANT ROLE TRANSFORMER_ROLE TO USER PGANALYTICS;

-- Verify
SHOW WAREHOUSES LIKE 'TRANSFORM_WH';
SHOW DATABASES LIKE 'SPRINGDALE%';
SHOW ROLES LIKE '%_ROLE';

-- Smoke-test role switching
USE ROLE TRANSFORMER_ROLE;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE SPRINGDALE_ANALYTICS;
SELECT CURRENT_ROLE() AS role, CURRENT_WAREHOUSE() AS warehouse, CURRENT_DATABASE() AS database;
